/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import com.sun.tools.javac.Main;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import pi2.DiscoDTO;
import pi2.DiscoDAO;

/**
 *
 * @author Raphael
 */
public class TelaListagemDisco extends javax.swing.JFrame {

private DefaultTableModel modeloTabela;

    public TelaListagemDisco() {
        initComponents();
        setLocationRelativeTo(null);
        String[] colunas = { "Título", "Artista", "Gênero", "Duração", "Lançamento", "Preço", "Estoque" };
        modeloTabela = new DefaultTableModel(null, colunas);
        listaDisco.setModel(modeloTabela);

       
        modeloTabela = (DefaultTableModel) listaDisco.getModel();
        atualizarTabela();
        

    this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowActivated(java.awt.event.WindowEvent e) {
            atualizarTabela();
        }
    });
    }

   private void atualizarTabela() {
    modeloTabela.setRowCount(0);
    DiscoDAO dao = new DiscoDAO();
    ArrayList<DiscoDTO> listaDiscos = new ArrayList<>( dao.listarDisco() );


    for (DiscoDTO disco : listaDiscos) {
        modeloTabela.addRow(new Object[] {
            disco.getTitulo(),
            disco.getArtista(),
            disco.getGenero(),
            disco.getDuracao(),
            disco.getLancamento(),
            disco.getPreco(),
            disco.getEstoque()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDisco = new javax.swing.JTable();
        btnCadastroD = new javax.swing.JToggleButton();
        btnVoltar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Catálogo de Discos");

        listaDisco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Artista", "Gênero", "Duração", "Lançamento", "Preço", "Quantidade", "Estoque"
            }
        ));
        jScrollPane1.setViewportView(listaDisco);

        btnCadastroD.setBackground(new java.awt.Color(234, 200, 62));
        btnCadastroD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastroD.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastroD.setText("Cadastrar Disco");
        btnCadastroD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroDActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(35, 42, 111));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastroD))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(307, 307, 307)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroD)
                    .addComponent(btnVoltar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroDActionPerformed
        new TelaCadastroDisco().setVisible(true);
        
    }//GEN-LAST:event_btnCadastroDActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCadastroD;
    private javax.swing.JToggleButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaDisco;
    // End of variables declaration//GEN-END:variables
}
