/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pi2.DiscoDAO;
import pi2.DiscoDTO;


/**
 *
 * @author Raphael
 */
public class TelaCadastroDisco extends javax.swing.JFrame {

    /**
     * Creates new form CadastroVIEW
     */

    public TelaCadastroDisco() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulotxt = new javax.swing.JTextField();
        Artistatxt = new javax.swing.JTextField();
        Generotxt = new javax.swing.JTextField();
        Duracaotxt = new javax.swing.JTextField();
        DataLancamentotxt = new javax.swing.JTextField();
        Precotxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCadastroD = new javax.swing.JToggleButton();
        btnVoltar = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        Estoquetxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitulotxtActionPerformed(evt);
            }
        });

        Artistatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArtistatxtActionPerformed(evt);
            }
        });

        Generotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerotxtActionPerformed(evt);
            }
        });

        Duracaotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuracaotxtActionPerformed(evt);
            }
        });

        DataLancamentotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataLancamentotxtActionPerformed(evt);
            }
        });

        Precotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecotxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Título");

        jLabel2.setText("Artista ou Banda");

        jLabel3.setText("Gênero");

        jLabel4.setText("Duração (em minutos)");

        jLabel5.setText("Data de Lançamento");

        jLabel6.setText("Preço");

        btnCadastroD.setBackground(new java.awt.Color(234, 200, 62));
        btnCadastroD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastroD.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastroD.setText("Cadastrar Disco");
        btnCadastroD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroDActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(35, 42, 111));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Cadastro de Disco");

        Estoquetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstoquetxtActionPerformed(evt);
            }
        });

        jLabel8.setText("Estoque");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(btnCadastroD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel7)
                        .addGap(20, 314, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Titulotxt)
                                .addComponent(Artistatxt)
                                .addComponent(jLabel3)
                                .addComponent(DataLancamentotxt)
                                .addComponent(Generotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Duracaotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(Precotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(46, 46, 46)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Estoquetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Titulotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(Artistatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Generotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Duracaotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataLancamentotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estoquetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(btnCadastroD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TitulotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitulotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitulotxtActionPerformed

    private void ArtistatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArtistatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArtistatxtActionPerformed

    private void GenerotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerotxtActionPerformed

    private void DuracaotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuracaotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DuracaotxtActionPerformed

    private void DataLancamentotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataLancamentotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataLancamentotxtActionPerformed

    private void PrecotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecotxtActionPerformed

    private void btnCadastroDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroDActionPerformed
    try {
        String titulo = Titulotxt.getText();
        String artista = Artistatxt.getText();
        String genero = Generotxt.getText();
        int duracao = Integer.parseInt(Duracaotxt.getText());
        int lancamento = Integer.parseInt(DataLancamentotxt.getText());
        BigDecimal preco = new BigDecimal(Precotxt.getText());
        int estoque = Integer.parseInt(Estoquetxt.getText());

        DiscoDTO disco = new DiscoDTO(0, titulo, artista, genero, duracao, lancamento, preco, estoque);
        DiscoDAO dao = new DiscoDAO();
        boolean sucesso = dao.cadastrarDisco(disco);

        if (sucesso) {
            JOptionPane.showMessageDialog(this, "✅ Disco cadastrado com sucesso!");
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "❌ Erro ao cadastrar o disco.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "⚠️ Verifique os campos numéricos.");
    }
    }//GEN-LAST:event_btnCadastroDActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void EstoquetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstoquetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstoquetxtActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Artistatxt;
    private javax.swing.JTextField DataLancamentotxt;
    private javax.swing.JTextField Duracaotxt;
    private javax.swing.JTextField Estoquetxt;
    private javax.swing.JTextField Generotxt;
    private javax.swing.JTextField Precotxt;
    private javax.swing.JTextField Titulotxt;
    private javax.swing.JToggleButton btnCadastroD;
    private javax.swing.JToggleButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
         Titulotxt.setText("");
    Artistatxt.setText("");
    Generotxt.setText("");
    Duracaotxt.setText("");
    DataLancamentotxt.setText("");
    Precotxt.setText("");
    Estoquetxt.setText("");
    }
}
