/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JPopupMenu;
import model.Permissao;
import model.PermissaoHelper;
import model.UsuarioDTO;
import pi2.FornecedorDAO;
import pi2.FornecedorDTO;

/**
 *
 * @author Raphael
 */
public class TelaListagemFornecedor extends javax.swing.JFrame {
    private UsuarioDTO usuarioLogado;
    /**
     * Creates new form TelaListagemFornecedor
     */
    private JPopupMenu popupMenu; // seu menu de contexto
    public TelaListagemFornecedor(UsuarioDTO usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
        initComponents();
        setLocationRelativeTo(null);
        carregarTabela();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowActivated(java.awt.event.WindowEvent e) {
        carregarTabela();
        configurarPopup();
    }
        });
    }
    private void configurarPopup() {
        // Supondo que popupMenu já tenha itens "Editar" e "Excluir"
        PermissaoHelper.configurarPermissoesListagem(
            popupMenu,
            usuarioLogado,
            Permissao.EDITAR_FORNECEDOR,
            Permissao.EXCLUIR_FORNECEDOR
        );
    }
private void carregarTabela() {
    FornecedorDAO dao = new FornecedorDAO();
    List<FornecedorDTO> lista = dao.listarFornecedores();

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Nome");
    model.addColumn("Contato");
    model.addColumn("CNPJ");

    for (FornecedorDTO f : lista) {
        model.addRow(new Object[]{
            f.getId(),
            f.getNome_Fornecedor(),
            f.getContato(),
            f.getCnpj()
        });
    }

    jTable1.setModel(model);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastroF = new javax.swing.JToggleButton();
        btnVoltar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCadastroF.setBackground(new java.awt.Color(234, 200, 62));
        btnCadastroF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastroF.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastroF.setText("Cadastrar Fornecedor");
        btnCadastroF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroFActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(35, 42, 111));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Contato", "CNPJ"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Fornecedores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastroF)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(194, 194, 194))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroF)
                    .addComponent(btnVoltar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroFActionPerformed
        new TelaCadastroFornecedor().setVisible(true);
         if (!usuarioLogado.podeCadastrarFornecedor()) {
        JOptionPane.showMessageDialog(this,
            "Você não tem permissão para cadastrar fornecedores.",
            "Acesso negado",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    }//GEN-LAST:event_btnCadastroFActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCadastroF;
    private javax.swing.JToggleButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
